/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useState } from 'react'
import { Alert, Box, Card, CardContent, Chip, CircularProgress, Divider, Grid, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from '@mui/material'
import { Area, AreaChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { getAPIErrorMessage } from '../../api/errors'
import { getCustomerPortalConnection, getCustomerPortalFTPEntitlements, getCustomerPortalInvoices, getCustomerPortalLiveTraffic, getCustomerPortalMe, getCustomerPortalPayments, getCustomerPortalServiceEntitlements, getCustomerPortalSubscriptions, type CustomerPortalConnection } from '../../api/customerPortal'

type PortalPageKind = 'profile' | 'connection' | 'traffic' | 'packages' | 'billing' | 'payments' | 'services'
const money = (amount: number) => `৳${Number(amount || 0).toLocaleString('en-BD', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const rate = (bps: number) => bps > 0 ? `${(bps / 1_000_000).toFixed(bps >= 10_000_000 ? 0 : 2)} Mbps` : '0 Mbps'
const display = (item?: string | number | null) => item === undefined || item === null || item === '' ? '—' : String(item)
const statusColor = (status?: string): 'default' | 'success' | 'warning' | 'error' => ['ACTIVE', 'PAID', 'COMPLETED', 'ONLINE'].includes((status || '').toUpperCase()) ? 'success' : ['PENDING', 'PARTIAL'].includes((status || '').toUpperCase()) ? 'warning' : ['EXPIRED', 'VOID', 'FAILED', 'DISCONNECTED'].includes((status || '').toUpperCase()) ? 'error' : 'default'

export default function PortalPage({ page }: { page: PortalPageKind }) {
  const [data, setData] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [samples, setSamples] = useState<{ time: string; download: number; upload: number }[]>([])
  useEffect(() => {
    let alive = true
    const loaders: Record<Exclude<PortalPageKind, 'traffic'>, () => Promise<any>> = { profile: getCustomerPortalMe, connection: getCustomerPortalConnection, packages: getCustomerPortalSubscriptions, billing: getCustomerPortalInvoices, payments: getCustomerPortalPayments, services: async () => Promise.all([getCustomerPortalServiceEntitlements(), getCustomerPortalFTPEntitlements()]) }
    const load = async () => { try { setError(''); const response = page === 'traffic' ? await Promise.all([getCustomerPortalConnection(), getCustomerPortalLiveTraffic()]) : await loaders[page](); if (!alive) return; const portalData = page === 'traffic' ? { ...(response[0] as CustomerPortalConnection), ...(response[1] as object) } : response; setData(portalData); if (page === 'traffic') { const connection = portalData as CustomerPortalConnection; setSamples((current) => [...current.slice(-23), { time: new Date().toLocaleTimeString('en-BD'), download: connection.download_bps / 1_000_000, upload: connection.upload_bps / 1_000_000 }]) } } catch (reason) { if (alive) setError(getAPIErrorMessage(reason, 'Unable to load portal information.')) } finally { if (alive) setLoading(false) } }
    void load(); const timer = page === 'traffic' ? window.setInterval(() => void load(), 5000) : undefined
    return () => { alive = false; if (timer) window.clearInterval(timer) }
  }, [page])
  const titles: Record<PortalPageKind, string> = { profile: 'My Profile', connection: 'My Connection', traffic: 'Live Traffic', packages: 'My Package', billing: 'Billing & Invoices', payments: 'Payment History', services: 'My Services' }
  if (loading && !data) return <Stack sx={{ minHeight: '40vh', alignItems: 'center', justifyContent: 'center' }} spacing={2}><CircularProgress /><Typography>Loading…</Typography></Stack>
  const connection = page === 'connection' || page === 'traffic' ? data as CustomerPortalConnection : null
  return <Stack spacing={3}><Box><Typography variant="h4" sx={{ fontWeight: 800 }}>{titles[page]}</Typography><Typography color="text.secondary">{page === 'traffic' ? 'Live router-synchronized usage, refreshed every 5 seconds.' : 'Your account information and service details.'}</Typography></Box>{error && <Alert severity="error">{error}</Alert>}{connection && <Connection connection={connection} traffic={page === 'traffic'} samples={samples} />}{page === 'profile' && <Profile data={data} />}{page === 'packages' && <Packages data={data ?? []} />}{page === 'billing' && <Invoices data={data ?? []} />}{page === 'payments' && <Payments data={data ?? []} />}{page === 'services' && <Services data={data} />}</Stack>
}
function Connection({ connection, traffic, samples }: { connection: CustomerPortalConnection; traffic: boolean; samples: { time: string; download: number; upload: number }[] }) { if (!connection.pppoe_username) return <Alert severity="info">No PPPoE internet account has been assigned to this customer yet.</Alert>; return <><Grid container spacing={2}><Metric label="Connection" value={connection.online ? 'ONLINE' : 'OFFLINE'} chip color={connection.online ? 'success' : 'default'} /><Metric label="Download" value={rate(connection.download_bps)} /><Metric label="Upload" value={rate(connection.upload_bps)} /></Grid>{traffic ? <Card><CardContent><Typography variant="h6" sx={{ fontWeight: 700 }}>Live speed graph</Typography><Box sx={{ height: 320, mt: 2 }}><ResponsiveContainer><AreaChart data={samples}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="time" minTickGap={32} /><YAxis unit=" Mbps" /><Tooltip /><Legend /><Area type="monotone" dataKey="download" name="Download" stroke="#1976d2" fill="#90caf9" /><Area type="monotone" dataKey="upload" name="Upload" stroke="#00897b" fill="#80cbc4" /></AreaChart></ResponsiveContainer></Box><Typography variant="caption" color="text.secondary">0 Mbps means the connection is offline or currently idle.</Typography></CardContent></Card> : <Card><CardContent><Grid container spacing={2}>{[['PPPoE username', connection.pppoe_username], ['Package', `${connection.package_code} — ${connection.package_name}`], ['Expiry date', connection.expiry_date], ['Router', `${connection.router_code} — ${connection.router_name}`], ['IP address', connection.ip_address || connection.static_ip_address], ['MAC address', connection.mac_address], ['Uptime', connection.uptime], ['RX Signal', connection.rx_signal_dbm !== undefined && connection.rx_signal_dbm !== null ? `${connection.rx_signal_dbm.toFixed(2)} dBm` : '—'], ['Last sync', connection.last_seen_at ? new Date(connection.last_seen_at).toLocaleString('en-BD') : '—']].map(([label, item]) => <Grid key={label} size={{ xs: 12, sm: 6, md: 3 }}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography>{display(item)}</Typography></Grid>)}</Grid></CardContent></Card>}</> }
function Metric({ label, value, chip, color }: { label: string; value: string; chip?: boolean; color?: 'default' | 'success' }) { return <Grid size={{ xs: 12, sm: 4 }}><Card><CardContent><Typography color="text.secondary">{label}</Typography>{chip ? <Chip sx={{ mt: 1 }} label={value} color={color} /> : <Typography variant="h4" sx={{ fontWeight: 800, mt: 1 }}>{value}</Typography>}</CardContent></Card></Grid> }
function Profile({ data }: { data: any }) { return <Card><CardContent><Grid container spacing={2}>{[['Customer code', data?.customer_code], ['Full name', data?.full_name], ['Mobile', data?.mobile], ['Alternative mobile', data?.alt_mobile], ['Email', data?.email], ['Status', data?.status], ['Billing day', data?.billing_day], ['Joining date', data?.joining_date], ['Agent / Reseller', data?.agent_name ? `${data.agent_code} — ${data.agent_name}` : 'Unassigned'], ['Agent contact', data?.agent_mobile], ['POP', data?.pop_name ? `${data.pop_code} — ${data.pop_name}` : '—'], ['Present address', data?.present_address], ['Permanent address', data?.permanent_address]].map(([label, item]) => <Grid key={label} size={{ xs: 12, md: label.includes('address') ? 12 : 4 }}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography>{display(item)}</Typography></Grid>)}</Grid></CardContent></Card> }
function Packages({ data }: { data: any[] }) { return <Grid container spacing={2}>{data.length ? data.map((item) => <Grid key={item.id} size={{ xs: 12, md: 6 }}><Card><CardContent><Stack direction="row" sx={{ justifyContent: 'space-between' }}><Typography variant="h6">{item.subscription_code}</Typography><Chip label={item.status} color={statusColor(item.status)} /></Stack><Divider sx={{ my: 2 }} /><Typography>PPPoE: {display(item.pppoe_username)}</Typography><Typography>Expiry: {display(item.expiry_date)}</Typography><Typography>Next billing: {display(item.next_billing_date)}</Typography><Typography>Due: {money(item.due_amount)}</Typography></CardContent></Card></Grid>) : <Grid size={12}><Alert severity="info">No active package was found.</Alert></Grid>}</Grid> }
function Invoices({ data }: { data: any[] }) { const due = data.reduce((sum, item) => sum + Number(item.due_amount || 0), 0); return <><Card><CardContent><Typography color="text.secondary">Current total due</Typography><Typography variant="h4" sx={{ fontWeight: 800 }}>{money(due)}</Typography></CardContent></Card><TableCard columns={['Invoice', 'Issue', 'Due date', 'Total', 'Due', 'Status']} rows={data.map((item) => [item.invoice_no, item.issue_date, item.due_date, money(item.total_amount), money(item.due_amount), item.status])} empty="No invoice found." /></> }
function Payments({ data }: { data: any[] }) { return <TableCard columns={['Receipt', 'Payment date', 'Amount', 'Method', 'Transaction', 'Status']} rows={data.map((item) => [item.receipt_no, item.payment_date, money(item.amount), item.method, item.transaction_id || '—', item.status])} empty="No payment found." /> }
function TableCard({ columns, rows, empty }: { columns: string[]; rows: any[][]; empty: string }) { return <Card><TableContainer><Table><TableHead><TableRow>{columns.map((column) => <TableCell key={column}>{column}</TableCell>)}</TableRow></TableHead><TableBody>{rows.length ? rows.map((row, index) => <TableRow key={index}>{row.map((item, cell) => <TableCell key={cell}>{display(item)}</TableCell>)}</TableRow>) : <TableRow><TableCell colSpan={columns.length} align="center">{empty}</TableCell></TableRow>}</TableBody></Table></TableContainer></Card> }
function Services({ data }: { data: any }) { const entries = [...(data?.[0] ?? []).map((item: any) => ({ name: item.service_name, detail: item.endpoint || item.username, status: item.status })), ...(data?.[1] ?? []).map((item: any) => ({ name: `FTP — ${item.username}`, detail: `${item.server_host}:${item.server_port}`, status: item.status }))]; return <Grid container spacing={2}>{entries.length ? entries.map((item: any, index: number) => <Grid key={index} size={{ xs: 12, md: 6 }}><Card><CardContent><Stack direction="row" sx={{ justifyContent: 'space-between' }}><Typography variant="h6">{item.name}</Typography><Chip label={item.status} color={statusColor(item.status)} /></Stack><Typography color="text.secondary" sx={{ mt: 1 }}>{item.detail || 'No endpoint configured'}</Typography></CardContent></Card></Grid>) : <Grid size={12}><Alert severity="info">No additional service is assigned.</Alert></Grid>}</Grid> }
