import apiClient from './client'

export type RouterStatus = 'ACTIVE' | 'INACTIVE' | 'MAINTENANCE'
export interface NetworkRouter { id: number; code: string; name: string; pop_id?: number; pop_name: string; host: string; api_port: number; api_username: string; use_tls: boolean; status: RouterStatus; remarks: string; connectivity_status: 'UNKNOWN' | 'ONLINE' | 'OFFLINE'; last_checked_at?: string; last_latency_ms: number; last_connection_error: string; last_tcp_error: string; last_api_error: string; credentials_configured: boolean; api_status: 'UNKNOWN' | 'AUTHENTICATED' | 'AUTH_FAILED'; last_authenticated_at?: string; router_identity: string; routeros_version: string; board_name: string; router_uptime: string; cpu_load: number; total_memory: number; free_memory: number }
export interface NetworkRouterInput { code: string; name: string; pop_id?: number; host: string; api_port: number; api_username: string; use_tls: boolean; status: RouterStatus; remarks: string }
export interface NetworkRouterHealth { id: number; router_id: number; observed_at: string; connectivity_status: string; api_status: string; latency_ms: number; cpu_load: number; total_memory: number; free_memory: number; router_uptime: string; tcp_error: string; api_error: string }
export interface NetworkRouterAlert { id: number; router_id: number; router_code: string; router_name: string; type: 'HIGH_CPU' | 'HIGH_MEMORY' | 'ROUTER_OFFLINE' | 'API_FAILURE'; severity: 'WARNING' | 'CRITICAL'; status: string; message: string; current_value: number; threshold: number; opened_at: string; last_observed_at: string; resolved_at?: string }
export interface NetworkRouterPPPoESession { id: number; router_id: number; router_code: string; router_name: string; username: string; service: string; caller_id: string; address: string; uptime: string; session_id: string; active: boolean; first_seen_at: string; last_seen_at: string; disconnected_at?: string; subscription_id?: number; subscription_code: string; subscription_status: string; customer_id?: number; customer_code: string; customer_name: string; package_id?: number; package_code: string; package_name: string }
export interface NetworkRouterPPPSecret { id: number; router_id: number; router_code: string; router_name: string; username: string; service: string; profile: string; caller_id: string; remote_address: string; disabled: boolean; present: boolean; last_seen_at: string; subscription_id?: number; subscription_code: string; subscription_status: string; customer_id?: number; customer_code: string; customer_name: string }
export interface NetworkPPPoESummary { active_sessions: number; mapped_sessions: number; unmapped_sessions: number }

export async function getNetworkRouters(): Promise<NetworkRouter[]> { return (await apiClient.get<{ routers: NetworkRouter[] | null }>('/network/routers')).data.routers ?? [] }
export async function createNetworkRouter(data: NetworkRouterInput): Promise<NetworkRouter> { return (await apiClient.post<NetworkRouter>('/network/routers', data)).data }
export async function updateNetworkRouter(id: number, data: NetworkRouterInput): Promise<NetworkRouter> { return (await apiClient.put<NetworkRouter>(`/network/routers/${id}`, data)).data }
export async function testNetworkRouterConnection(id: number): Promise<NetworkRouter> { return (await apiClient.post<NetworkRouter>(`/network/routers/${id}/test-connection`)).data }
export async function setNetworkRouterCredentials(id: number, password: string): Promise<NetworkRouter> { return (await apiClient.put<NetworkRouter>(`/network/routers/${id}/credentials`, { password })).data }
export async function syncNetworkRouterResource(id: number): Promise<NetworkRouter> { return (await apiClient.post<NetworkRouter>(`/network/routers/${id}/sync-resource`)).data }
export async function getNetworkRouterHistory(id: number, limit = 100): Promise<NetworkRouterHealth[]> { return (await apiClient.get<{ history: NetworkRouterHealth[] }>(`/network/routers/${id}/history`, { params: { limit } })).data.history }
export async function getNetworkRouterAlerts(status = 'ACTIVE'): Promise<NetworkRouterAlert[]> { return (await apiClient.get<{ alerts: NetworkRouterAlert[] }>('/network/router-alerts', { params: { status } })).data.alerts }
export async function getNetworkRouterPPPoESessions(id: number, active = true): Promise<NetworkRouterPPPoESession[]> { return (await apiClient.get<{ sessions: NetworkRouterPPPoESession[] }>(`/network/routers/${id}/pppoe-sessions`, { params: { active, limit: 1000 } })).data.sessions }
export async function getNetworkPPPoESummary(): Promise<NetworkPPPoESummary> { return (await apiClient.get<NetworkPPPoESummary>('/network/pppoe-summary')).data }
export async function getNetworkPPPoESessions(active = true): Promise<NetworkRouterPPPoESession[]> { return (await apiClient.get<{ sessions: NetworkRouterPPPoESession[] }>('/network/pppoe-sessions', { params: { active, limit: 5000 } })).data.sessions }
export async function mapNetworkPPPoESession(id: number, subscriptionId: number): Promise<void> { await apiClient.post(`/network/pppoe-sessions/${id}/map`, { subscription_id: subscriptionId }) }
export async function getNetworkRouterPPPSecrets(): Promise<NetworkRouterPPPSecret[]> { return (await apiClient.get<{ secrets: NetworkRouterPPPSecret[] }>('/network/ppp-secrets', { params: { present: true } })).data.secrets }
export async function mapNetworkRouterPPPSecret(id: number, subscriptionId: number): Promise<void> { await apiClient.post(`/network/ppp-secrets/${id}/map`, { subscription_id: subscriptionId }) }
