import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Alert, Box, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { getCustomers, type Customer } from '../../api/customers'
import { createServiceEntitlement, deleteServiceEntitlement, getServiceEntitlements, updateServiceEntitlement, type ServiceEntitlement, type ServiceEntitlementRequest } from '../../api/serviceEntitlements'
import { getAPIErrorMessage } from '../../api/errors'
const blank=():ServiceEntitlementRequest=>({customer_id:0,service_type:'JELLYFIN',service_name:'',username:'',password:'',endpoint:'',status:'ACTIVE',quota_gb:0,remarks:''})
export default function ServiceEntitlements(){
 const [rows,setRows]=useState<ServiceEntitlement[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[form,setForm]=useState(blank()),[editing,setEditing]=useState<ServiceEntitlement|null>(null),[open,setOpen]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{try{const [items,customerData]=await Promise.all([getServiceEntitlements(),getCustomers()]);setRows(items);setCustomers(customerData.customers)}catch(e){setError(getAPIErrorMessage(e,'Failed to load services.'))}}
 useEffect(()=>{
  const initialLoad=window.setTimeout(()=>{
   void load()
  },0)
  return ()=>window.clearTimeout(initialLoad)
 },[])
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return q?rows.filter(r=>[r.customer_code,r.customer_name,r.service_type,r.service_name,r.username,r.endpoint,r.status].join(' ').toLowerCase().includes(q)):rows},[rows,search])
 const show=(row?:ServiceEntitlement)=>{setEditing(row||null);setForm(row?{customer_id:row.customer_id,subscription_id:row.subscription_id,service_type:row.service_type,service_name:row.service_name,username:row.username,password:'',endpoint:row.endpoint,status:row.status,expiry_at:row.expiry_at?.slice(0,10),quota_gb:row.quota_gb,remarks:row.remarks}:blank());setOpen(true)}
 const save=async(e:FormEvent)=>{e.preventDefault();try{setBusy(true);setError('');if(editing)await updateServiceEntitlement(editing.id,form);else await createServiceEntitlement(form);setOpen(false);await load()}catch(err){setError(getAPIErrorMessage(err,'Failed to save service.'))}finally{setBusy(false)}}
 const remove=async(row:ServiceEntitlement)=>{if(!confirm(`Delete ${row.service_name}?`))return;try{await deleteServiceEntitlement(row.id);await load()}catch(e){setError(getAPIErrorMessage(e,'Failed to delete service.'))}}
 return <Box><Box sx={{display:'flex',justifyContent:'space-between',mb:3}}><Box><Typography variant="h4" sx={{fontWeight:700}}>Service Entitlements</Typography><Typography color="text.secondary">Customer-owned Jellyfin, IPTV and Cloud Storage access.</Typography></Box><Button variant="contained" onClick={()=>show()}>Add Service</Button></Box>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Card><CardContent><TextField fullWidth label="Search customer or service" value={search} onChange={e=>setSearch(e.target.value)} sx={{mb:2}}/><Table><TableHead><TableRow><TableCell>#</TableCell><TableCell>Customer</TableCell><TableCell>Type</TableCell><TableCell>Service</TableCell><TableCell>Username</TableCell><TableCell>Endpoint</TableCell><TableCell>Status</TableCell><TableCell>Actions</TableCell></TableRow></TableHead><TableBody>{filtered.map((r,i)=><TableRow key={r.id}><TableCell>{i+1}</TableCell><TableCell>{r.customer_code}<br/>{r.customer_name}</TableCell><TableCell>{r.service_type}</TableCell><TableCell>{r.service_name}</TableCell><TableCell>{r.username||'—'}</TableCell><TableCell>{r.endpoint||'—'}</TableCell><TableCell>{r.status}</TableCell><TableCell><Button onClick={()=>show(r)}>Edit</Button><Button color="error" onClick={()=>void remove(r)}>Delete</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
 <Dialog open={open} onClose={()=>!busy&&setOpen(false)} fullWidth maxWidth="md"><Box component="form" onSubmit={save}><DialogTitle>{editing?'Edit':'Add'} Service Entitlement</DialogTitle><DialogContent dividers><Grid container spacing={2}><Grid size={{xs:12,md:6}}><TextField required select fullWidth label="Customer" value={form.customer_id||''} onChange={e=>setForm({...form,customer_id:Number(e.target.value)})}>{customers.map(c=><MenuItem key={c.id} value={c.id}>{c.customer_code} — {c.full_name}</MenuItem>)}</TextField></Grid><Grid size={{xs:12,md:6}}><TextField required select fullWidth label="Service Type" value={form.service_type} onChange={e=>setForm({...form,service_type:e.target.value})}>{['JELLYFIN','IPTV','CLOUD_STORAGE'].map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField></Grid><Grid size={{xs:12,md:6}}><TextField required fullWidth label="Service Name" value={form.service_name} onChange={e=>setForm({...form,service_name:e.target.value})}/></Grid><Grid size={{xs:12,md:6}}><TextField fullWidth label="Endpoint / URL" value={form.endpoint} onChange={e=>setForm({...form,endpoint:e.target.value})}/></Grid><Grid size={{xs:12,md:6}}><TextField fullWidth label="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></Grid><Grid size={{xs:12,md:6}}><TextField fullWidth type="password" label={editing?'New Password (blank keeps current)':'Password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Grid><Grid size={{xs:12,md:4}}><TextField select fullWidth label="Status" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['ACTIVE','SUSPENDED','EXPIRED','DISABLED'].map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField></Grid><Grid size={{xs:12,md:4}}><TextField fullWidth type="date" label="Expiry" value={form.expiry_at||''} slotProps={{inputLabel:{shrink:true}}} onChange={e=>setForm({...form,expiry_at:e.target.value})}/></Grid><Grid size={{xs:12,md:4}}><TextField fullWidth type="number" label="Quota GB" value={form.quota_gb} onChange={e=>setForm({...form,quota_gb:Number(e.target.value)})}/></Grid><Grid size={12}><TextField fullWidth multiline label="Remarks" value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})}/></Grid></Grid></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" variant="contained" disabled={busy||!form.customer_id||!form.service_name}>{busy?'Saving...':'Save'}</Button></DialogActions></Box></Dialog></Box>
}
